//sad
pipeline {
    agent { label 'build-node' } // 빌드 전용 노드

    environment {
        GRADLE_OPTS = '-Xmx256m -XX:+UseSerialGC' // t2.nano 환경 최적화
    }

    stages {

        stage('Checkout') {
            steps {
                script {
                    echo "Building branch: main"
                    git url: 'https://github.com/bumpy103/simple_chat_backend.git', branch: 'main'
                }
            }
        }

        // stage('Checkout') {
        //     steps {
        //         script {
        //             echo "Building branch: ${env.BRANCH_NAME}"
        //             git url: 'https://github.com/bumpy103/simple_chat_backend.git', branch: "${env.BRANCH_NAME}"
        //         }
        //     }
        // }

        stage('Build') {
            steps {
                dir('scb') {
                    sh './gradlew build --no-daemon'
                }
            }
        }


        stage('Archive Artifact') {
            steps {
                script {
                    echo "Archiving build artifacts..."
                    archiveArtifacts artifacts: 'build/libs/*.jar', fingerprint: true
                }
            }
        }
    }

    post {
        success {
            echo "CI build succeeded for branch ${env.BRANCH_NAME}!"
        }
        failure {
            echo "CI build failed for branch ${env.BRANCH_NAME}. Check logs!"
        }
    }
}